<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="Divino.OperationResult" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Riok.Mapperly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FcgUsers.Domain\FcgUsers.Domain.csproj" />
    <ProjectReference Include="..\FcgUsers.SharedKernel\FcgUsers.SharedKernel.csproj" />
  </ItemGroup>

</Project>
