apiVersion: v1
kind: Secret

metadata:
  name: fcg-users-api-secret
  namespace: fcg-platform

  labels:
    app.kubernetes.io/name: fcg-users-api
    app.kubernetes.io/instance: fcg-users-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: fcg-platform
    app.kubernetes.io/managed-by: kubectl

type: Opaque

stringData:
  ConnectionStrings__Default: "Host=postgres;Port=5432;Database=fcgusers-db;Username=fcg;Password=fcg123"
  ConnectionStrings__Rabbitmq: "amqp://fcg:fcg123@rabbitmq:5672"
  JwtSettings__SecurityKey: "FcgUsers_Secret_Key_2026_High_Security_Token"
