apiVersion: v1
kind: Service

metadata:
  name: fcg-users-api
  namespace: fcg-platform

  labels:
    app.kubernetes.io/name: fcg-users-api
    app.kubernetes.io/instance: fcg-users-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: fcg-platform
    app.kubernetes.io/managed-by: kubectl

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: fcg-users-api

  ports:
    - name: http
      port: 7010
      targetPort: 7010
