apiVersion: v1
kind: ConfigMap

metadata:
  name: fcg-users-worker-config
  namespace: fcg-platform

  labels:
    app.kubernetes.io/name: fcg-users-worker
    app.kubernetes.io/instance: fcg-users-worker
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: fcg-platform
    app.kubernetes.io/managed-by: kubectl

data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Serilog__MinimumLevel__Default: "Warning"
  Serilog__MinimumLevel__Override__Microsoft: "Warning"
  Serilog__MinimumLevel__Override__System: "Warning"
  Serilog__Properties__ApplicationName: "FcgUsers.Worker"
  MassTransit__RetryLimit: "5"
  MassTransit__MinIntervalSeconds: "1"
  MassTransit__MaxIntervalSeconds: "30"
  MassTransit__IntervalDeltaSeconds: "2"
