apiVersion: v1
kind: Secret

metadata:
  name: fcg-users-worker-secret
  namespace: fcg-platform

  labels:
    app.kubernetes.io/name: fcg-users-worker
    app.kubernetes.io/instance: fcg-users-worker
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: fcg-platform
    app.kubernetes.io/managed-by: kubectl

type: Opaque

stringData:
  ConnectionStrings__Rabbitmq: "amqp://fcg:fcg123@rabbitmq:5672"
  ConnectionStrings__Default: "Host=postgres;Port=5432;Database=fcgusers-db;Username=fcg;Password=fcg123"
