<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Repositories\Users\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="IDomainAssembly.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FcgUsers.SharedKernel\FcgUsers.SharedKernel.csproj" />
  </ItemGroup>

</Project>
