name: 🐳 Publish Docker Images

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: 🐳 Build & Push Images
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: 📦 Restore
        run: dotnet restore

      - name: 🔨 Build
        run: dotnet build --no-restore --configuration Release

      - name: 🧪 Execute Unit Tests
        run: |
          dotnet test tests/FcgUsers.UnitTests/FcgUsers.UnitTests.csproj \
            --no-build \
            --configuration Release

      - name: 🧪 Execute Integration Tests
        run: |
          dotnet test tests/FcgUsers.IntegrationTests/FcgUsers.IntegrationTests.csproj \
            --no-build \
            --configuration Release

      - name: 🐳 Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🏷️ Extract Version
        id: version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: 🚀 Build & Push API
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/FcgUsers.Api/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/fcg-users-api:${{ steps.version.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/fcg-users-api:latest

      - name: 🚀 Build & Push Worker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/FcgUsers.Worker/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/fcg-users-worker:${{ steps.version.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/fcg-users-worker:latest